# Generated by Django 4.2.8 on 2024-01-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="category",
            field=models.TextField(default="교육용", max_length=50),
            preserve_default=False,
        ),
    ]
